export const string = {
  Acount: "Email*",
  Password: "Password*",
  HolderEmail: "@gmail.com",
  ConfirmPassword: "ConfirmPassword*",
  Name: "Name*",
  Sex: "Sex",
  DateOfBirth: "DateOfBirth",
  Phone: "Phone",
  Confirm: "Confirm*",
  Login: "Login",
  Logout: "Logout",
  ForgotPassword: "ForgotPassword",
  RememberPassword: "RememberPassword",
  ComentResigter: "You have account. Please sign in?",
  SignIn: "Sign in",
  ErrorEmail: "Wrong email",
  ErrorPhone: "Wrong phone",
  ErrorPass: "Password longer than 6 characters",
  Send: "Send",
  ErrorConfirm: "Confirm Password was wrong ",
};
