export const string = {
<<<<<<< HEAD
  Acount: "Email*",
  Password: "Password*",
  HolderEmail: "@gmail.com",
  ConfirmPassword: "ConfirmPassword*",
  Name: "Name*",
  Sex: "Sex",
  DateOfBirth: "DateOfBirth",
  Phone: "Phone",
  Confirm: "Confirm*",
  Login: "Login",
  Logout: "Logout",
  ForgotPassword: "ForgotPassword",
  RememberPassword: "RememberPassword",
  ComentResigter: "You have account. Please sign in?",
  SignIn: "Sign in",
  ErrorEmail: "Wrong email",
  ErrorPhone: "Wrong phone",
  ErrorPass: "Password longer than 6 characters",
  Send: "Send",
  ErrorConfirm: "Confirm Password was wrong ",
=======
  Acount: "Tài khoản",
  Password: "Mật khẩu",
  HolderEmail: "@gmail.com",
  ConfirmPassword: "Xác nhận mật khẩu",
  Name: "Tên",
  Sex: "Giới tính",
  DateOfBirth: "Ngày sinh",
  Phone: "Số điện thoại",
  Confirm: "Xác nhận",
  Login: "Đăng nhập",
  Logout: "Đăng xuất",
  ForgotPassword: "Quên mật khẩu",
  RememberPassword: "Lưu mật khẩu",
  ComentResigter: "Nếu bạn chưa có tài khoản thì?",
  Resigter: "Đăng ký",
>>>>>>> develop
};
